version: "3.8"

services:
  api_golang:
    container_name: apigolang
    build:
      context: api-golang
      dockerfile: DockerFile
    ports:
      - 8080:8080
  api_node:
    container_name: apinode
    build:
      context: api-node
      dockerfile: Dockerfile
    ports:
      - 7070:7070
